[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Serial Monitor Options
monitor_speed = 115200

; Library Dependencies
lib_deps =
    olikraus/U8g2 @ ^2.35.9